[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if joker_tally > G.GAME.max_jokers then G.GAME.max_jokers = joker_tally end"
position = "after"
match_indent = true
payload = '''

SMODS.calculate_context(
	{
		mystery_pack = {
			joker_obtained = card
		}
	}
)

'''
