[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.play_sound.sound_settings = G.SETTINGS.SOUND"
position = "at"
match_indent = true
payload = '''
G.ARGS.play_sound.sound_settings = MysteryPack.Sound.get_sound_settings()
'''

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.push.sound_settings = G.SETTINGS.SOUND"
position = "at"
match_indent = true
payload = '''
-- I removed this patch's effect cos it made the settings slider reset to zero: I do not want that to occur. Will it work?
-- it broke it, so I added it back
G.ARGS.push.sound_settings = MysteryPack.Sound.get_sound_settings()
'''
