[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "hands = {"
position = "before"
match_indent = true
payload = '''

mystery_pack = {
	enhancement_replacements = {
		more_bonus = 0,
		more_mult = 0,
		fake_transparencies = 0
	},

},

'''
