[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.E_MANAGER:update(self.real_dt)"
position = "before"
match_indent = true
payload = '''

if MysteryPack and MysteryPack.Sound and MysteryPack.Sound.temp_muted then
	MysteryPack.Sound.remaining_mute_time = MysteryPack.Sound.remaining_mute_time - dt
	if not (MysteryPack.Sound.remaining_mute_time > 0) then
		MysteryPack.Sound.temp_muted = false
		G.SETTINGS.SOUND.music_volume = MysteryPack.Sound.previous_volume
	end
end

'''
